services:
  - type: web
    name: portfolio-fadil
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio_fadil.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "une-cle-secrete-tres-forte"
      - key: DJANGO_SETTINGS_MODULE
        value: "portfolio_fadil.settings"
      - key: PYTHON_VERSION
        value: "3.11"
